name: LinksPlugin
version: 1.0.0
main: me.example.linksplugin.LinksPlugin
api-version: 1.21

commands:
  discord:
    description: Discord link
  store:
    description: Store link
  vote:
    description: Vote link
